apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.sockshop-staging.adafbdf6312c411eb8aa80249bac460d-1023403331.us-west-2.elb.amazonaws.com
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop-staging.svc.cluster.local
